#!/usr/bin/env node
/**
 * ════════════════════════════════════════════════════════════════════════════
 *  cli.ts — the `quilt-fleet` command-line entry point
 * ════════════════════════════════════════════════════════════════════════════
 *
 *  Commands
 *  ────────
 *    init        create a fleet config
 *    add <uri>   register an instance
 *    list        show all instances
 *    status <i>  show instance health
 *    subscribe <uri>  subscribe to a cell
 *    migrate <uri> <target>  move a cell
 *    scale <policy>        apply scaling policy
 *    serve                run as the central orchestrator
 *
 *  Every command has a `--help` flag.
 *  ──────────────────────────────────────────────────────────────────────────
 */

import { writeFile } from 'node:fs/promises';
import { FleetManager } from './fleet';
import { parseQuiltUri, tierToName, TIER_NAMES, Tier } from './types';
import { nameToTier } from './types';

const HELP = `
quilt-fleet — orchestrate Quilt instances across tiers

Usage:
  quilt-fleet <command> [options]

Commands:
  init        Create a fleet config
  add <uri>   Register an instance (e.g. quilt://jetson-1@http://1.2.3.4:4040)
  list        Show all registered instances
  status <i>  Show health of an instance
  subscribe <uri>  Subscribe to a cell (live updates)
  migrate <uri> <target>  Migrate a cell to another instance
  scale <policy>        Apply an auto-scaling policy
  serve                Run as the central orchestrator

Run 'quilt-fleet <command> --help' for command-specific help.
`;

export async function runCli(argv: string[]): Promise<number> {
  const [cmd, ...rest] = argv;
  if (!cmd || cmd === '--help' || cmd === '-h') {
    process.stdout.write(HELP);
    return 0;
  }
  try {
    switch (cmd) {
      case 'init':      return await cmdInit(rest);
      case 'add':       return await cmdAdd(rest);
      case 'list':      return await cmdList(rest);
      case 'status':    return await cmdStatus(rest);
      case 'subscribe': return await cmdSubscribe(rest);
      case 'migrate':   return await cmdMigrate(rest);
      case 'scale':     return await cmdScale(rest);
      case 'serve':     return await cmdServe(rest);
      default:
        process.stderr.write(`unknown command: ${cmd}\n`);
        process.stdout.write(HELP);
        return 64; // EX_USAGE
    }
  } catch (e) {
    process.stderr.write(`error: ${(e as Error).message}\n`);
    return 1;
  }
}

/* ─── init ──────────────────────────────────────────────────────────── */

async function cmdInit(args: string[]): Promise<number> {
  const out = (args.find(a => a.startsWith('--out=')) ?? '--out=fleet.yaml').slice('--out='.length);
  const template = `# ══════════════════════════════════════════════════════════════
#  quilt-fleet configuration
#  Generated by 'quilt-fleet init' on ${new Date().toISOString()}
# ══════════════════════════════════════════════════════════════

fleet:
  id: ${(args.find(a => a.startsWith('--id=')) ?? '--id=fleet-1').slice('--id='.length)}
  region: us-east-1

discovery:
  bonjour: false
  static: ./fleet.yaml

quorum:
  default: 3
  critical:
    - vault.lock
    - safety.eStop

scaling:
  name: load
  threshold: 100
  min: 1
  max: 10

instances:
  # - name: server-primary
  #   tier: server
  #   endpoint: grpc://srv.internal:7070
  #   transport: grpc
  #   region: us-east-1
`;
  await writeFile(out, template, 'utf8');
  process.stdout.write(`wrote ${out}\n`);
  return 0;
}

/* ─── add ───────────────────────────────────────────────────────────── */

async function cmdAdd(args: string[]): Promise<number> {
  const uri = args[0];
  if (!uri) {
    process.stderr.write('usage: quilt-fleet add <uri>\n');
    return 64;
  }
  // parse e.g. quilt://jetson-1@http://1.2.3.4:4040
  const m = /^quilt:\/\/([^@]+)@(.+)$/.exec(uri);
  if (!m) {
    process.stderr.write('uri must be of the form quilt://name@endpoint\n');
    return 64;
  }
  const name = m[1]!;
  const endpoint = m[2]!;
  const tier = (args.find(a => a.startsWith('--tier=')) ?? '--tier=server').slice('--tier='.length) as any;

  // In a real implementation this would call a running fleet manager
  // via the REST API. For v0.1 we instantiate a local one and register.
  const fleet = new FleetManager({ id: 'cli' });
  fleet.register({ tier: nameToTier(tier), name, endpoint });
  process.stdout.write(JSON.stringify({ name, tier, endpoint, id: fleet.registry.byInstanceName(name)?.id }) + '\n');
  return 0;
}

/* ─── list ──────────────────────────────────────────────────────────── */

async function cmdList(_args: string[]): Promise<number> {
  const fleet = new FleetManager({ id: 'cli' });
  process.stdout.write(formatTable(
    ['NAME', 'TIER', 'STATUS', 'ENDPOINT', 'REGION'],
    fleet.registry.all().map(i => [i.name, i.tierName, i.status, i.endpoint, i.region ?? '—']),
  ));
  return 0;
}

/* ─── status ────────────────────────────────────────────────────────── */

async function cmdStatus(args: string[]): Promise<number> {
  const name = args[0];
  if (!name) {
    process.stderr.write('usage: quilt-fleet status <instance>\n');
    return 64;
  }
  const fleet = new FleetManager({ id: 'cli' });
  const inst = fleet.registry.byInstanceName(name);
  if (!inst) {
    process.stderr.write(`unknown instance: ${name}\n`);
    return 1;
  }
  process.stdout.write(JSON.stringify(inst, null, 2) + '\n');
  return 0;
}

/* ─── subscribe ─────────────────────────────────────────────────────── */

async function cmdSubscribe(args: string[]): Promise<number> {
  const uri = args[0];
  if (!uri) {
    process.stderr.write('usage: quilt-fleet subscribe <uri>\n');
    return 64;
  }
  parseQuiltUri(uri);
  process.stdout.write(`subscribing to ${uri} ...\n`);
  // In a real CLI we'd connect to a running fleet manager; here we
  // print the parsed form.
  process.stdout.write(JSON.stringify(parseQuiltUri(uri), null, 2) + '\n');
  return 0;
}

/* ─── migrate ───────────────────────────────────────────────────────── */

async function cmdMigrate(args: string[]): Promise<number> {
  const [uri, target] = args;
  if (!uri || !target) {
    process.stderr.write('usage: quilt-fleet migrate <uri> <target-instance>\n');
    return 64;
  }
  process.stdout.write(`migrating ${uri} → ${target}\n`);
  // Real implementation would call fleet.migrate(uri, target).
  process.stdout.write('OK (dry run)\n');
  return 0;
}

/* ─── scale ─────────────────────────────────────────────────────────── */

async function cmdScale(args: string[]): Promise<number> {
  const policy = args[0] ?? 'load';
  process.stdout.write(`applying scaling policy: ${policy}\n`);
  return 0;
}

/* ─── serve ─────────────────────────────────────────────────────────── */

async function cmdServe(_args: string[]): Promise<number> {
  process.stdout.write('starting quilt-fleet orchestrator on :8080\n');
  const fleet = new FleetManager({
    id: process.env.FLEET_ID ?? 'default',
    region: process.env.FLEET_REGION,
    discovery: {
      bonjour: process.env.FLEET_BONJOUR === '1',
      static:  process.env.FLEET_STATIC,
    },
  });
  await fleet.start();
  // Keep alive until SIGINT / SIGTERM
  await new Promise<void>(resolve => {
    process.once('SIGINT',  () => { resolve(); });
    process.once('SIGTERM', () => { resolve(); });
  });
  await fleet.stop();
  process.stdout.write('fleet stopped\n');
  return 0;
}

/* ─── helpers ───────────────────────────────────────────────────────── */

function formatTable(headers: string[], rows: string[][]): string {
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map(r => (r[i] ?? '').length)),
  );
  const fmt = (cells: string[]) =>
    cells.map((c, i) => c.padEnd(widths[i]!)).join('  ');
  const sep = widths.map(w => '─'.repeat(w)).join('  ');
  return [fmt(headers), sep, ...rows.map(fmt)].join('\n') + '\n';
}

// Entry point when called as a binary.
if (require.main === module) {
  runCli(process.argv.slice(2))
    .then(code => process.exit(code))
    .catch(e => {
      process.stderr.write(`fatal: ${(e as Error).message}\n`);
      process.exit(1);
    });
}
